services:
  - type: web
    name: django-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn yourprojectname.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: how2cheatwiki61.settings
